void reset();
void black(short mode);
void red(short mode);
void green(short mode);
void yellow(short mode);
void blue(short mode);
void purple(short mode);
void cyan(short mode);
void white(short mode);
void selecionarCor(char peca[3]);